<div id="insure-info" style="display:none">
    <dt>Insurance available</dt>
    <dd>
        <ul>
            <li>
                <input name="s_insurance" id="s_insurance" type="checkbox" value="1" class="checkbox">
                <label for="s_insurance" >
                    Include insurance <br>
                    <b><span id="s_insurance_cost"></span></b>
                </label>
            </li>
        </ul>
    </dd>
</div>

<script>

    function InsuranceShipping(info) {

        var data, infoNode, costNode, insuranceCheckbox;

        var init = function(info) {
            data = info;
            infoNode = jQuery('#insure-info');
            insuranceCheckbox = jQuery('#s_insurance');
            costNode = jQuery('#s_insurance_cost');
            addEvents();
        }

        var addEvents = function() {
            if (data.length) {
                jQuery('.sp-methods input[name=shipping_method]').on('change', function() {
                    hideInfo();
                    var value = jQuery(this).val();
                    data.forEach(function(item) {
                        if (item.isEnabled && ~value.indexOf(item.method)) {
                            showInfo(item);
                        }
                    })
                })
            }
        }

        var hideInfo = function() {
            infoNode.css('display', 'none');
            insuranceCheckbox.prop('checked', false);
        }

        var showInfo = function(item) {
            infoNode.css('display', 'block');
            costNode.html(item.message)
        }

        init(info);
    }

    new InsuranceShipping(<?php echo json_encode($this->getInsuranceData()) ?>)

</script>
